### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by Feng-Sir0** [Rodger-Huang/SYSU-HCP-at-ImageCLEF-VQA-Med-2021#1]
I'm honored to learn about such an excellent work. Could you please provide me with the training set or a link to the training set for VQA-Med-2021?

**Comment by Rodger-Huang** [comment]
@Feng-Sir0 You can download the training set from this link (https://drive.google.com/file/d/1ovF5HF4t49ZJ8YMmaydfvcfeOf08h3yR/view?usp=sharing).
